"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dense-only vector-store bridge.

The Node server (src/kb/store.ts) calls this Python gRPC service, which wraps pymilvus
(Milvus Lite) for dense ANN retrieval. This is a deliberate capability subset of the
Python original (~/Downloads/python app/kb/milvus_client.py): that project ran Milvus
Standalone and pushed dense + sparse(BM25 Function) + hybrid(RRFRanker) all into Milvus.
Here only dense lives in Milvus; BM25 stays in-process on the Node side (SQLite text)
and hybrid is fused with the existing reciprocal-rank-fusion code. See src/kb/store.ts.
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import kb_store_pb2 as _kb_store_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class KbStoreStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> KbStoreAsyncStub: ...
    Upsert: _grpc.UnaryUnaryMultiCallable[_kb_store_pb2.UpsertRequest, _kb_store_pb2.UpsertResponse]
    Search: _grpc.UnaryUnaryMultiCallable[_kb_store_pb2.SearchRequest, _kb_store_pb2.SearchResponse]
    Count: _grpc.UnaryUnaryMultiCallable[_kb_store_pb2.CountRequest, _kb_store_pb2.CountResponse]
    Delete: _grpc.UnaryUnaryMultiCallable[_kb_store_pb2.DeleteRequest, _kb_store_pb2.DeleteResponse]
    Drop: _grpc.UnaryUnaryMultiCallable[_kb_store_pb2.DropRequest, _kb_store_pb2.DropResponse]
    Flush: _grpc.UnaryUnaryMultiCallable[_kb_store_pb2.FlushRequest, _kb_store_pb2.FlushResponse]

@_typing.type_check_only
class KbStoreAsyncStub(KbStoreStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Upsert: _aio.UnaryUnaryMultiCallable[_kb_store_pb2.UpsertRequest, _kb_store_pb2.UpsertResponse]  # type: ignore[assignment]
    Search: _aio.UnaryUnaryMultiCallable[_kb_store_pb2.SearchRequest, _kb_store_pb2.SearchResponse]  # type: ignore[assignment]
    Count: _aio.UnaryUnaryMultiCallable[_kb_store_pb2.CountRequest, _kb_store_pb2.CountResponse]  # type: ignore[assignment]
    Delete: _aio.UnaryUnaryMultiCallable[_kb_store_pb2.DeleteRequest, _kb_store_pb2.DeleteResponse]  # type: ignore[assignment]
    Drop: _aio.UnaryUnaryMultiCallable[_kb_store_pb2.DropRequest, _kb_store_pb2.DropResponse]  # type: ignore[assignment]
    Flush: _aio.UnaryUnaryMultiCallable[_kb_store_pb2.FlushRequest, _kb_store_pb2.FlushResponse]  # type: ignore[assignment]

class KbStoreServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Upsert(
        self,
        request: _kb_store_pb2.UpsertRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kb_store_pb2.UpsertResponse, _abc.Awaitable[_kb_store_pb2.UpsertResponse]]: ...

    @_abc_1.abstractmethod
    def Search(
        self,
        request: _kb_store_pb2.SearchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kb_store_pb2.SearchResponse, _abc.Awaitable[_kb_store_pb2.SearchResponse]]: ...

    @_abc_1.abstractmethod
    def Count(
        self,
        request: _kb_store_pb2.CountRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kb_store_pb2.CountResponse, _abc.Awaitable[_kb_store_pb2.CountResponse]]: ...

    @_abc_1.abstractmethod
    def Delete(
        self,
        request: _kb_store_pb2.DeleteRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kb_store_pb2.DeleteResponse, _abc.Awaitable[_kb_store_pb2.DeleteResponse]]: ...

    @_abc_1.abstractmethod
    def Drop(
        self,
        request: _kb_store_pb2.DropRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kb_store_pb2.DropResponse, _abc.Awaitable[_kb_store_pb2.DropResponse]]: ...

    @_abc_1.abstractmethod
    def Flush(
        self,
        request: _kb_store_pb2.FlushRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_kb_store_pb2.FlushResponse, _abc.Awaitable[_kb_store_pb2.FlushResponse]]: ...

def add_KbStoreServicer_to_server(servicer: KbStoreServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
