"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Dense-only vector-store bridge.

The Node server (src/kb/store.ts) calls this Python gRPC service, which wraps pymilvus
(Milvus Lite) for dense ANN retrieval. This is a deliberate capability subset of the
Python original (~/Downloads/python app/kb/milvus_client.py): that project ran Milvus
Standalone and pushed dense + sparse(BM25 Function) + hybrid(RRFRanker) all into Milvus.
Here only dense lives in Milvus; BM25 stays in-process on the Node side (SQLite text)
and hybrid is fused with the existing reciprocal-rank-fusion code. See src/kb/store.ts.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Row(_message.Message):
    """A single knowledge chunk row as stored in Milvus. The dense vector is the only indexed
    field; the scalar fields are carried so Search can return full hits without a SQLite join.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DENSE_FIELD_NUMBER: _builtins.int
    QUESTION_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    SECTION_PATH_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    CATEGORY_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    question: _builtins.str
    answer: _builtins.str
    section_path: _builtins.str
    content_type: _builtins.str
    category: _builtins.str
    @_builtins.property
    def dense(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        dense: _abc.Iterable[_builtins.float] | None = ...,
        question: _builtins.str = ...,
        answer: _builtins.str = ...,
        section_path: _builtins.str = ...,
        content_type: _builtins.str = ...,
        category: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "category", b"category", "content_type", b"content_type", "dense", b"dense", "id", b"id", "question", b"question", "section_path", b"section_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Row: _TypeAlias = Row  # noqa: Y015

@_typing.final
class UpsertRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ROWS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rows(self) -> _containers.RepeatedCompositeFieldContainer[Global___Row]: ...
    def __init__(
        self,
        *,
        rows: _abc.Iterable[Global___Row] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rows", b"rows"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpsertRequest: _TypeAlias = UpsertRequest  # noqa: Y015

@_typing.final
class UpsertResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpsertResponse: _TypeAlias = UpsertResponse  # noqa: Y015

@_typing.final
class SearchRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VECTOR_FIELD_NUMBER: _builtins.int
    TOP_K_FIELD_NUMBER: _builtins.int
    CATEGORY_FIELD_NUMBER: _builtins.int
    top_k: _builtins.int
    category: _builtins.str
    """empty = no category filter"""
    @_builtins.property
    def vector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        vector: _abc.Iterable[_builtins.float] | None = ...,
        top_k: _builtins.int = ...,
        category: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category", b"category", "top_k", b"top_k", "vector", b"vector"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchRequest: _TypeAlias = SearchRequest  # noqa: Y015

@_typing.final
class Hit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    QUESTION_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    SECTION_PATH_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    CATEGORY_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    score: _builtins.float
    """COSINE similarity: higher = more similar"""
    question: _builtins.str
    answer: _builtins.str
    section_path: _builtins.str
    content_type: _builtins.str
    category: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        score: _builtins.float = ...,
        question: _builtins.str = ...,
        answer: _builtins.str = ...,
        section_path: _builtins.str = ...,
        content_type: _builtins.str = ...,
        category: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "category", b"category", "content_type", b"content_type", "id", b"id", "question", b"question", "score", b"score", "section_path", b"section_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Hit: _TypeAlias = Hit  # noqa: Y015

@_typing.final
class SearchResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HITS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def hits(self) -> _containers.RepeatedCompositeFieldContainer[Global___Hit]: ...
    def __init__(
        self,
        *,
        hits: _abc.Iterable[Global___Hit] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hits", b"hits"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchResponse: _TypeAlias = SearchResponse  # noqa: Y015

@_typing.final
class CountRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CountRequest: _TypeAlias = CountRequest  # noqa: Y015

@_typing.final
class CountResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CountResponse: _TypeAlias = CountResponse  # noqa: Y015

@_typing.final
class DeleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        ids: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ids", b"ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteRequest: _TypeAlias = DeleteRequest  # noqa: Y015

@_typing.final
class DeleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteResponse: _TypeAlias = DeleteResponse  # noqa: Y015

@_typing.final
class DropRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DropRequest: _TypeAlias = DropRequest  # noqa: Y015

@_typing.final
class DropResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DropResponse: _TypeAlias = DropResponse  # noqa: Y015

@_typing.final
class FlushRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FlushRequest: _TypeAlias = FlushRequest  # noqa: Y015

@_typing.final
class FlushResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FlushResponse: _TypeAlias = FlushResponse  # noqa: Y015
